@istest 
public class NGS_S1_TypesResAvailabiltiy_IFS_WS_test {
@istest static void unitttt(){
         NGS_S1_TypesResourceAvailabiltiy_IFS_WS.shiftAvailability sd = new NGS_S1_TypesResourceAvailabiltiy_IFS_WS.shiftAvailability();
              sd.employeeId='text';
              sd.shiftStartTime=system.today();
              sd.shiftDate=system.today();
              sd.shiftStartTime=system.today();
              sd.shiftFinishTime=system.today();
    }
    @istest static void unittts(){
         NGS_S1_TypesResourceAvailabiltiy_IFS_WS.shifts ss = new NGS_S1_TypesResourceAvailabiltiy_IFS_WS.shifts();
         
      
        
    }
}